### ISSUE TITLE
Can not generate or find the libgl_useful.so file

### ISSUE THREAD

**Issue by createS0ftware** [ldo/3D-Compass#1]
Hi 

i could not find the libgl_useful.so file - i don't think it was generated - how can i generate it ?

Thanks for your help

**Comment by ldo** [comment]
Did you follow the build instructions?

**Comment by ldo** [comment]
I’ll take that as a “no”.

**Comment by createS0ftware** [comment]
Hi sorry for the delay in replying - i have been super busy and with a terrible flu so non-essential tasks got pushed aside. I will work on it this weekend again. I did follow the build instructions and i got past that initial error i mentioned above but i have a new error - i will investigate.

Thanks
