### ISSUE TITLE
'invalid package declaration' in AIDE (Android IDE compiler java jni for tablet = fine)

### ISSUE THREAD

**Issue by picpic020960** [ldo/3D-Compass#2]
Bonjour,

Clone the github in AIDE , but before compile ,  'invalid package declaration' for each java src file.
Help please
The project is intresting  :  GL and camera
Regards

**Comment by ldo** [comment]
Did you follow the build instructions?

**Comment by picpic020960** [comment]
Build instruction not applicable in AIDE
Can you make test with AIDE.  Exists. Free version in playstore with github interface. Very good product for mobility
(Install the NDK from settings = 790 mo )

**Comment by ldo** [comment]
Learn to follow the build instructions first.

**Comment by picpic020960** [comment]
Not cool  ! 
AIDE is packaged so SDK and NDK path not available (In data/data but non rooted device)
I thought the problem is maybe in package name , not on the ndk/sdk (ok for other ndk project)
If you test all the AIDE users thanks you.
(Sorry for my bad english)
Regards
