### ISSUE TITLE
for AIDE users ...

### ISSUE THREAD

**Issue by picpic020960** [ldo/3D-Compass#3]
Don't forget to move the source members in the right folder  : 
nz.gen.geek_central.Compass3d or nz.gen.geek_central.Gluseful

NB  :  SDK and NDK. paths not needed . AIDE know it  !

**Comment by ldo** [comment]
Have you tried following the build instructions?

**Comment by picpic020960** [comment]
Not needed
With right path src structure AIDE make the job.

Works fine. 

NB  :  install the NDK from settings AIDE menu

**Comment by ldo** [comment]
So, no problem then.
